export const LOGIN_ACTION = "LOGIN_ACTION";
export const SIGNUP_ACTION = "SIGNUP_ACTION";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const SET_SIGNUP_ERROR = "SET_SIGNUP_ERROR";
export const SET_AUTH_SUCCESS = "SET_AUTH_SUCCESS";
export const COUNTRY_WEATHER_ACTION ="COUNTRY_WEATHER_ACTION";
export const COUNTRY_WEATHER_SAGA_ACTION ="COUNTRY_WEATHER_SAGA_ACTION"

// async
export const LOGIN_SAGA_ACTION = "LOGIN_SAGA_ACTION";
export const SIGNUP_SAGA_ACTION = "SIGNUP_SAGA_ACTION";
export const AUTO_LOGIN_TOKEN_SAGA = "AUTO_LOGIN_TOKEN_SAGA";
